[qola]
aiter_commit = "d32b0cb62ecc32bb1a858e8437d58eb9b3856af6"    # pinned AITER submodule commit
rocm_versions = ["7.1"]

[build]
architectures = ["gfx950"]

# Static modules from optCompilerConfig.json
[[modules]]
name = "module_gemm_a4w4_asm"

[[modules]]
name = "module_gemm_a4w4_blockscale"